/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "on-secondary-container": "#283789",
              "on-primary-container": "#fffeff",
              "accent-pink": "#FF64C8",
              "surface-bright": "#faf9f8",
              "tertiary-fixed-dim": "#ccc5c0",
              "secondary": "#4958aa",
              "tertiary-container": "#7a7571",
              "primary-fixed-dim": "#a8c8ff",
              "tertiary": "#615d59",
              "inverse-surface": "#2f3130",
              "on-error-container": "#93000a",
              "accent-sky": "#62AEF0",
              "on-error": "#ffffff",
              "primary-container": "#0075de",
              "background": "#faf9f8",
              "on-tertiary-container": "#ffffff",
              "primary-fixed": "#d5e3ff",
              "surface-container-high": "#e9e8e7",
              "on-tertiary": "#ffffff",
              "inverse-on-surface": "#f1f0ef",
              "ink-muted": "#8A8682",
              "accent-green": "#1AAE39",
              "secondary-fixed": "#dee0ff",
              "surface-container-lowest": "#ffffff",
              "on-tertiary-fixed-variant": "#4a4642",
              "on-background": "#1a1c1c",
              "border-hairline": "#E6E6E6",
              "ink-primary": "#111111",
              "surface-dim": "#dadad9",
              "on-tertiary-fixed": "#1e1b18",
              "secondary-fixed-dim": "#bac3ff",
              "on-secondary-fixed-variant": "#303f91",
              "primary": "#005db2",
              "surface-container-low": "#f4f3f2",
              "accent-purple": "#D6B6F6",
              "surface": "#FFFFFF",
              "surface-container-highest": "#e3e2e1",
              "on-primary": "#ffffff",
              "on-primary-fixed": "#001b3c",
              "surface-container": "#eeeeed",
              "secondary-container": "#97a5fe",
              "on-surface": "#1a1c1c",
              "tertiary-fixed": "#e8e1dc",
              "surface-variant": "#e3e2e1",
              "outline-variant": "#c1c6d5",
              "inverse-primary": "#a8c8ff",
              "outline": "#717784",
              "error": "#ba1a1a",
              "error-container": "#ffdad6",
              "on-secondary": "#ffffff",
              "accent-teal": "#2A9D99",
              "on-surface-variant": "#414753",
              "on-primary-fixed-variant": "#00468a",
              "on-secondary-fixed": "#00105b",
              "surface-tint": "#005eb4"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "sm": "12px",
              "lg": "24px",
              "margin-mobile": "16px",
              "gutter": "24px",
              "md": "16px",
              "xl": "32px",
              "max-width-content": "1200px",
              "xs": "8px",
              "base": "4px",
              "xxl": "48px"
          },
          "fontFamily": {
              "label-caps": ["Inter", "sans-serif"],
              "display-lg": ["Inter", "sans-serif"],
              "body-base": ["Inter", "sans-serif"],
              "page-title-mobile": ["Inter", "sans-serif"],
              "page-title": ["Inter", "sans-serif"],
              "section-heading": ["Inter", "sans-serif"],
              "feature-title": ["Inter", "sans-serif"],
              "body-sm": ["Inter", "sans-serif"]
          },
          "fontSize": {
              "label-caps": ["12px", { "lineHeight": "1.3", "letterSpacing": "0.05em", "fontWeight": "600" }],
              "display-lg": ["64px", { "lineHeight": "1.0", "letterSpacing": "-0.03em", "fontWeight": "700" }],
              "body-base": ["16px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
              "page-title-mobile": ["28px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
              "page-title": ["36px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "section-heading": ["22px", { "lineHeight": "1.25", "letterSpacing": "-0.01em", "fontWeight": "700" }],
              "feature-title": ["20px", { "lineHeight": "1.4", "letterSpacing": "-0.005em", "fontWeight": "600" }],
              "body-sm": ["14px", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "400" }]
          }
      }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
